# Generated by Django 5.2 on 2025-06-12 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mojaaplikacja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zamowienia', models.DateTimeField(auto_now_add=True)),
                ('nr_zamowienia', models.CharField(max_length=50)),
                ('calkowita_kwota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PozycjaZamowienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.IntegerField(default=1)),
                ('cena_jednostkowa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mojaaplikacja.produkty')),
                ('zamowienie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pozycje', to='mojaaplikacja.zamowienie')),
            ],
        ),
    ]
