# Generated by Django 5.2 on 2025-05-29 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Description',
            new_name='description',
        ),
    ]
